# Use the official Python image from the Docker Hub
FROM python:3.8

# Set the working directory
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    wget \
    unzip \
    git \
    && rm -rf /var/lib/apt/lists/*

# Download and install Ninja
RUN wget https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip \
    && unzip ninja-linux.zip -d /usr/local/bin/ \
    && update-alternatives --install /usr/bin/ninja ninja /usr/local/bin/ninja 1 --force \
    && rm ninja-linux.zip

# Install Git LFS
RUN apt-get update && apt-get install -y git-lfs \
    && rm -rf /var/lib/apt/lists/*

# Initialize Git LFS
RUN git lfs install


# Copy the entire Face_feature-main folder to the container
COPY Face_feature-main /app/Face_feature-main

# Set the working directory to the notebook directory within Face_feature-main
WORKDIR /app/Face_feature-main/notebook

# Copy the requirements file from the correct path
COPY Face_feature-main/notebook/requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt \
    && pip install wandb omegaconf git+https://github.com/openai/CLIP.git pytorch_fid piq einops timm pyfacer jupyter

# Set CUDA_HOME environment variable
ENV CUDA_HOME=/usr/local/cuda



# Specify the command to run main.py instead of Jupyter notebook
CMD ["python", "main.py"]
